version: '3'

services:
  orius_db:
    image: mongo:4.0.8
    container_name: orius_mongo
    restart: unless-stopped
    command: mongod --auth
    env_file: orius/environment/orius_env

  orius:
    build: .
    image: orius:devel
    restart: on-failure
    container_name: orius_container
    command: make run
    env_file: orius/environment/orius_env
    volumes:
      - .:/app
      - mongodbdata:/data/db

volumes:
  static_data:
