version: '3'
services:

  orius_db:
    image: mariadb:10.3
    env_file: orius/environment/orius_env

  orius:
    build: .
    image: orius:devel
    logging:
        driver: none
    restart: on-failure
    container_name: orius_container
    command: make run
    env_file: orius/environment/orius_env
    volumes:
      - .:/app
      - static_data:/app/static
    depends_on:
      - orius_db

volumes:
  static_data:

