version: '3'
services:

  mongo:
    image: mongo
    restart: always
    logging:
        driver: none
    env_file: orius/environment/orius_env
    networks:
      - app-tier
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d
      - logs:/var/log/mongodb/

  orius:
    build: .
    image: orius:devel
    logging:
        driver: none
    restart: on-failure
    container_name: orius_container
    command: make run
    depends_on:
      - mongo
    networks:
      - app-tier
    env_file: orius/environment/orius_env
    volumes:
      - .:/app
      - mongodbdata:/data/db

  rmlog:
    image: orius:devel
    restart: on-failure
    container_name: orius_rmlog
    command: "./daemons/rmlog /var/log/mongodb/"
    depends_on:
      - mongo
    volumes:
      - logs:/var/log/mongodb/

networks:
  app-tier:
    driver: bridge


volumes:
  static_data:
  mongodbdata:
  logs:
